### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by maryjeck** [kaste/SublimeLinter-contrib-ruff#3]
```
DPI mode: per-monitor v2
startup, version: 4180 windows x64 channel: stable
executable: /D/Program Files/sublime_text/sublime_text.exe
application: /D/Program Files/sublime_text
working dir: /D/Maryjeck/Desktop
packages path: /D/Program Files/sublime_text/Data/Packages
state path: /D/Program Files/sublime_text/Data/Local
zip path: /D/Program Files/sublime_text/Packages
zip path: /D/Program Files/sublime_text/Data/Installed Packages
ignored_packages: ["Anaconda", "LSP-pylsp"]
pre session restore time: 0.157566
font face "0xProto Nerd Font Mono" has different widths for bold characters, disabling to prevent text reflow
startup time: 0.232566
first paint time: 0.273566
reloading python 3.3 plugin BracketHighlighter.bh_core
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin ANSIescape.ansi
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin LSP-basedpyright.boot
reloading python 3.3 plugin BracketHighlighter.bh_logging
reloading python 3.3 plugin BracketHighlighter.bh_plugin
reloading python 3.3 plugin BracketHighlighter.bh_popup
reloading python 3.3 plugin BracketHighlighter.bh_regions
reloading python 3.3 plugin BracketHighlighter.bh_remove
reloading python 3.3 plugin BracketHighlighter.bh_rules
reloading python 3.3 plugin BracketHighlighter.bh_search
reloading python 3.3 plugin BracketHighlighter.bh_swapping
reloading python 3.3 plugin BracketHighlighter.bh_wrapping
reloading python 3.3 plugin BracketHighlighter.support
reloading python 3.3 plugin ChineseLocalizations.Localization
reloading python 3.3 plugin ConvertChineseCharacters.convertChineseCharacters
reloading python 3.3 plugin FileHeader.FileHeader
reloading python 3.3 plugin JsFormat.js_formatter
reloading plugin LSP-file-watcher-chokidar.watcher
reloading plugin LSP-html.data_types
reloading plugin LSP-html.plugin
reloading plugin LSP-json.commands
reloading plugin LSP-json.plugin
reloading plugin LSP-json.schema_store
reloading plugin LSP.boot
reloading python 3.3 plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin Package Control.plugin
reloading plugin python-black.commands
reloading plugin SublimeLinter-contrib-ruff.linter
reloading plugin SublimeLinter.__allo__
reloading plugin SublimeLinter._init
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.quick_actions
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin ConvertToUTF8.ConvertToUTF8
plugins loaded
[LSP-basedpyright][INFO] Adding extra analysis paths (prepend = False): ['D:\\Program Files\\sublime_text\\Lib\\python38', 'D:\\Program Files\\sublime_text\\Lib\\python3', 'D:\\Program Files\\sublime_text\\Data\\Lib\\python38', 'D:\\Program Files\\sublime_text\\Packages', 'D:\\Program Files\\sublime_text\\Data\\Packages']
Package Control: Skipping automatic upgrade, last run at 2024-09-15 10:39:06, next run at 2024-09-15 18:39:06 or after
ignored packages updated to: ["Anaconda", "LSP-pylsp", "SublimeLinter-contrib-ruff"]
unloading plugin SublimeLinter-contrib-ruff.linter
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Removed package "SublimeLinter-contrib-ruff"
ignored packages updated to: ["Anaconda", "LSP-pylsp"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: pausing indexer
ignored packages updated to: ["Anaconda", "LSP-pylsp", "SublimeLinter-contrib-ruff"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed package "SublimeLinter-contrib-ruff" 1.1.5
ignored packages updated to: ["Anaconda", "LSP-pylsp"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter-contrib-ruff.linter
Package Control: resuming indexer
reloading settings Packages/User/Preferences.sublime-settings
SublimeLinter-lift: remove_python_version_file("SublimeLinter-contrib-ruff"), ok.
unloading plugin SublimeLinter-contrib-ruff.linter
reloading python 3.3 plugin SublimeLinter-contrib-ruff.linter
Traceback (most recent call last):
  File "D:\Program Files\sublime_text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Program Files\sublime_text\Lib\python33\sublime_plugin.py", line 1686, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "D:\Program Files\sublime_text\Data\Installed Packages\SublimeLinter-contrib-ruff.sublime-package\linter.py", line 8, in <module>
ImportError: No module named 'SublimeLinter'
Unable to open /D/Program Files/sublime_text/Data/Packages/SublimeLinter/SublimeLinter.sublime-settings

```

**Comment by kaste** [comment]
I think that's a Sublime Text core bug.  I had this error but it still worked after that.  On a restart there were no errors at all.  

The bug is basically that it triggers `reloading python 3.3 plugin SublimeLinter-contrib-ruff.linter`.  When upgrading it tries to reload the plugin under Python v3.3 which very obviously fails as SublimeLinter runs on Python v3.8.
